from __future__ import annotations

from contextlib import contextmanager
from typing import Any, Iterator, Protocol


class DatabaseBackend(Protocol):

    def execute(self, sql: str, params: dict[str, Any] | None = None) -> int: ...

    def query(self, sql: str, params: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...

    def query_one(self, sql: str, params: dict[str, Any] | None = None) -> dict[str, Any] | None: ...

    @contextmanager
    def transaction(self) -> Iterator[None]:
        yield

    def batch_execute(self, sql: str, param_sets: list[dict[str, Any]]) -> int: ...

    def json_param(self, name: str) -> str: ...

    def json_safe(self, value: Any) -> Any: ...

    def json_safe_dict(self, value: Any) -> dict: ...

    def json_safe_list(self, value: Any) -> list: ...

    def json_decode(self, value: Any) -> Any: ...

    def json_decode_dict(self, value: Any) -> dict: ...

    def json_decode_list(self, value: Any) -> list: ...

    def ilike(self, col: str, param: str) -> str: ...

    def regex_match(self, col: str, param: str) -> str: ...

    def t(self, canonical_name: str) -> str: ...

    def cron_col(self, canonical: str) -> str: ...

    @property
    def reboot_epoch(self) -> int: ...

    def increment_epoch(self) -> int: ...

    def set_meta(self, key: str, value: str) -> None: ...

    def get_meta(self, key: str) -> dict[str, str] | None: ...
